### ISSUE TITLE
User plugin registering guests users

### ISSUE THREAD

**Issue by thedoofus** [rainlab/user-plugin#544]
In the docs (linked below) under guest users, it says you can create a guest by passing the `'is_guest' => true"` - is this the create method because none is shown in the example given. You also get a validation error because a `first_name` is required. Is it possible to bypass this?

https://github.com/rainlab/user-plugin/blob/master/docs/auth-manager.md

It also states that you can convert a guest user to a registered user by providing password and confirmation along with the email address to the create method, and you won't receive a "email already taken" error - but this doesn't seem to be the case.

I can get round this by getting the user, running the `convertToRegistered()` method setting the password, and name manually.

On that, the `convertToRegistered()` method keeps the guest group as the primary group - shouldn't this get updated to the `Registered` group at this point?

**Comment by daftspunk** [comment]
This does look like a bit of a schemozzle...

Everything you've mentioned here is correct. The `first_name` attribute is required in this version, so populate it with "Guest" or something or remove it from the validation rules (not recommended).

This has been fixed, docs and tests have been updated in 9a0d5ebed4bdfa163e5aca39378d66819ca9e816

Thanks! Let me know if you spot any other inconsistencies.

**Comment by thedoofus** [comment]
Hi @daftspunk 

Sorry to bring this one up again. The frontend Register component still includes the unique validation on the email address. So trying to register an account, with an email that's previously been used for a guest fails when using this component.

https://github.com/rainlab/user-plugin/blob/f850474f38a71f43976097217cdeee627fee77a6/components/Registration.php#L108

**Comment by markandmedia** [comment]
I can confirm this is still an issue.

If a visitor first registers as a guest and later wants to create an account using the same email address, there is no way to proceed. Registration fails, and the password recovery does not work either.

At that point, the user cannot continue using that email address without assistance from an administrator.

**Comment by daftspunk** [comment]
This has been fixed in v3.5.2

- Related 75e8910cd7cdfa2eab986e294f62fbdab7d61593

**Comment by markandmedia** [comment]
I tested this and confirmed it is now possible to create an account after registering as a guest. 

However, this allows multiple users to share the same email address, which introduces a new issue: after creating the new account, users are unable to log in. I assume this is because the system attempts to match the credentials against one of the duplicate guest accounts.

**Comment by daftspunk** [comment]
Hey @markandmedia 

I added a test for this and it seems to be working normally: https://github.com/rainlab/user-plugin/commit/49cfc6e1b6bcfceb718e7614903dad62b7ac5fbd

However I found a bug with 2FA authentication when there are guest accounts, although I'm not sure this is related:
https://github.com/rainlab/user-plugin/commit/91504023de551a59d7ab7c0758a2b549b140cef9

Can you give me some more information on how to reproduce it?

**Comment by markandmedia** [comment]
Hello @daftspunk 

Thanks for looking into this. I tested the process in the following order:
	1.	First, I created a guest account (works).
	2.	Next, I registered a new account (also works after the latest update).
	3.	Then, I logged out and tried logging in with the newly created account (does not work).

The error message displayed is "These credentials do not match our records." That's why I assume the plugin is trying to log in using the first email address it finds, which still belongs to the guest account.

**Comment by daftspunk** [comment]
> 1. First, I created a guest account (works).

How did you create the guest, was it via the backend or frontend?

**Comment by markandmedia** [comment]
This was in the front-end, In a local standard Meloncart template/shop. I dont't think this affects anything?

**Comment by daftspunk** [comment]
Thanks for that, it helped pin down the issue

The actual bug is in this plugin's two-factor login path (which is the default even when users don't have 2FA set up)

Please update to v3.5.3 to see if it helps

**Comment by markandmedia** [comment]
Just tested it after the update and it’s fixed! Thanks for the quick support!
